[phases.setup]
nixPkgs = ["nodejs_18", "python312", "python312Packages.pip", "python312Packages.virtualenv", "zlib"]

[phases.install]
cmds = [
  "npm ci",
  "python3 -m venv /opt/venv",
  ". /opt/venv/bin/activate && pip install --upgrade pip setuptools wheel",
  ". /opt/venv/bin/activate && pip install --only-binary=:all: --no-build-isolation -r ml-service/requirements.txt"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = ". /opt/venv/bin/activate && bash start.sh"
