[phases.setup]
nixPkgs = ["nodejs_18", "python312", "python312Packages.pip"]

[phases.install]
cmds = [
  "npm ci",
  "pip install -r ml-service/requirements.txt"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "bash start.sh"

